using System.Text;

namespace GrtReloadingToolkit.Reports;

/// <summary>
/// Installs DokuWiki report pages into GRT's <c>doku/&lt;lang&gt;/report/</c> folders so the
/// plugin's analysis notes and charts can be pulled into a printable GRT report.
/// GRT's doku files use bare-CR line endings and UTF-8 without BOM.
/// </summary>
public static class ReportTemplates
{
    /// <summary>(filename without extension, page body) — body uses '\n', written as '\r'.</summary>
    private static readonly (string Name, string Body)[] Pages =
    {
        ("toolkit-full", """
        ======Load Workup - Full Report======
        ^ **File:** ^ //"~~file.path~~"// ^

        {{  ~~caliber.drawing.png~~?360x520}}

        ^  Recipe  ^^^^
        |  Caliber  |  ~~work.CaliberName~~  |  Firearm  |  ~~work.GunName~~  |
        |  Bullet  |  ~~work.ProjectileName~~  |  Bullet weight  |  ~~work.mp~~  |
        |  Powder  |  ~~work.PropellantName~~  |  Charge  |  ~~work.mc~~  |
        |  Ladder  |  ~~work.ladderlist~~  |  Ba  |  ~~work.Ba("#.000000")~~  |
        |  Seating depth  |  ~~work.gdepth~~  |  COAL (L6/OAL)  |  ~~work.oal~~  |
        |  Case length (L3/CL)  |  ~~work.caselen~~  |  Case volume  |  ~~work.casevol~~  |

        =====Predicted (current charge)=====
        ^  Pmax  ^  V0  ^  Barrel time  ^  Fill  ^  Burnt  ^  Recoil  ^
        |  ~~result.MaxPressure("-#")~~  |  ~~result.MuzzleVelocity("-#")~~  |  ~~result.BarrelTime("#.0000")~~  |  ~~result.LoadRatio("-#.0%")~~  |  ~~result.BurnRatio("-#.0%")~~  |  ~~result.RecoilEnergy~~  |

        {{~~result.diagramcurves.png~~?100%}}

        =====1. Charge ladder / OCW=====
        {{~~result.picture.ocw_chart.png~~?100%}}
        ~~result.Note("OCW Analysis")~~

        =====2. Seating depth (test)=====
        {{~~result.picture.seating_chart.png~~?100%}}
        ~~result.Note("Seating Depth Analysis")~~

        =====3. Barrel calibration=====
        ~~result.Note("Barrel Calibration")~~

        =====4. Powder temperature coefficients=====
        ~~result.Note("Powder Temp Coefficients")~~

        =====5. Case volume=====
        ~~result.Note("Case Volume")~~

        =====6. Seating depth (geometry)=====
        ~~result.Note("Seating Depth (geometry)")~~

        =====7. Load sheet / cost=====
        ~~result.Note("Load Sheet")~~

        //Reloading Toolkit - full workup. Each numbered section fills in when you run that tool and
        //"Write ... to GRT load"; an empty section just means that step hasn't been done yet.//
        """),

        ("toolkit-ocw", """
        ======Ladder / OCW Report======
        ^ **File:** ^ //"~~file.path~~"// ^

        ^  Load  ^^
        |  Caliber  |  ~~work.CaliberName~~  |
        |  Bullet  |  ~~work.ProjectileName~~  |
        |  Powder  |  ~~work.PropellantName~~  |
        |  Charge (sim)  |  ~~work.mc~~  |
        |  Ladder steps  |  ~~work.ladderlist~~  |
        |  Ba  |  ~~work.Ba("#.000000")~~  |

        =====Charge-ladder analysis=====
        {{~~result.picture.ocw_chart.png~~?100%}}

        ~~result.Note("OCW Analysis")~~

        =====GRT simulation at the selected charge=====
        ^  V0  ^  Pmax  ^  Barrel time  ^
        |  ~~result.MuzzleVelocity("-#")~~  |  ~~result.MaxPressure("-#")~~  |  ~~result.BarrelTime("#.0000")~~  |

        //Generated by the Reloading Toolkit — Ladder / OCW analyzer. Run it, then "Write note to GRT load".//
        """),

        ("toolkit-seating", """
        ======Seating-Depth Report======
        ^ **File:** ^ //"~~file.path~~"// ^

        ^  Load  ^^
        |  Caliber  |  ~~work.CaliberName~~  |
        |  Bullet  |  ~~work.ProjectileName~~  |
        |  Powder  |  ~~work.mc~~, ~~work.PropellantName~~  |
        |  Seating depth  |  ~~work.gdepth~~  |
        |  COAL (L6/OAL)  |  ~~work.oal~~  |

        =====Seating / jump analysis=====
        {{~~result.picture.seating_chart.png~~?100%}}

        ~~result.Note("Seating Depth Analysis")~~

        //Generated by the Reloading Toolkit — Seating-depth analyzer.//
        """),

        ("toolkit-calibration", """
        ======Barrel Calibration Report======
        ^ **File:** ^ //"~~file.path~~"// ^

        ^  Load  ^^
        |  Caliber  |  ~~work.CaliberName~~  |
        |  Powder  |  ~~work.PropellantName~~  |
        |  Charge  |  ~~work.mc~~  |
        |  Ba (in file)  |  ~~work.Ba("#.000000")~~  |

        =====Measured vs. simulated muzzle velocity=====
        ~~result.Note("Barrel Calibration")~~

        =====Powder temperature coefficients=====
        ~~result.Note("Powder Temp Coefficients")~~

        //Generated by the Reloading Toolkit — Barrel calibration / Powder temp coefficients.//
        """),

        ("toolkit-loadsheet", """
        ======Load Sheet======
        ^ **File:** ^ //"~~file.path~~"// ^

        ^  Recipe  ^^
        |  Caliber  |  ~~work.CaliberName~~  |
        |  Bullet  |  ~~work.ProjectileName~~ (~~work.mp~~)  |
        |  Powder  |  ~~work.PropellantName~~  |
        |  Charge  |  ~~work.mc~~  |
        |  Seating depth  |  ~~work.gdepth~~  |
        |  COAL (L6/OAL)  |  ~~work.oal~~  |
        |  Case length (L3/CL)  |  ~~work.caselen~~  |
        |  Case volume  |  ~~work.casevol~~  |

        ^  Predicted  ^^
        |  V0  |  ~~result.MuzzleVelocity~~  |
        |  Pmax  |  ~~result.MaxPressure~~  |
        |  Fill  |  ~~result.LoadRatio("-#.0%")~~  |
        |  Burnt  |  ~~result.BurnRatio("-#.0%")~~  |

        =====Cost & notes=====
        ~~result.Note("Load Sheet")~~

        {{~~result.diagramcurves.png~~?100%}}

        //Generated by the Reloading Toolkit — Load card / label ("Write load-sheet note").//
        """),
    };

    private static readonly (string Name, string Label)[] Links =
    {
        ("toolkit-full", "Toolkit — Full load workup (all sections)"),
        ("toolkit-ocw", "Toolkit — Ladder / OCW report"),
        ("toolkit-seating", "Toolkit — Seating-depth report"),
        ("toolkit-calibration", "Toolkit — Barrel calibration report"),
        ("toolkit-loadsheet", "Toolkit — Load sheet (recipe + cost)"),
    };

    /// <summary>The GRT install root (parent of <c>doku/</c>), inferred from the running exe.</summary>
    public static string? InferGrtRoot()
    {
        // exe lives in <root>/plugins/ReloadingToolkit/
        var dir = new DirectoryInfo(AppContext.BaseDirectory);
        for (int up = 0; up < 5 && dir != null; up++, dir = dir.Parent)
            if (Directory.Exists(Path.Combine(dir.FullName, "doku")))
                return dir.FullName;
        return null;
    }

    /// <summary>Writes the report pages into every <c>doku/&lt;lang&gt;/report</c> folder. Returns a log.</summary>
    public static List<string> Install(string grtRoot)
    {
        var log = new List<string>();
        string doku = Path.Combine(grtRoot, "doku");
        if (!Directory.Exists(doku)) { log.Add($"no doku folder under {grtRoot}"); return log; }

        var enc = new UTF8Encoding(false);
        int langs = 0;
        foreach (var langDir in Directory.GetDirectories(doku))
        {
            string reportDir = Path.Combine(langDir, "report");
            if (!Directory.Exists(reportDir)) continue;
            langs++;
            string lang = Path.GetFileName(langDir);

            foreach (var (name, body) in Pages)
            {
                string path = Path.Combine(reportDir, name + ".txt");
                File.WriteAllText(path, body.Replace("\r\n", "\n").Replace("\n", "\r"), enc);
                log.Add($"{lang}: wrote {name}.txt");
            }

            string startPath = Path.Combine(reportDir, "start.txt");
            if (File.Exists(startPath))
            {
                string start = File.ReadAllText(startPath);
                var missing = Links.Where(l => !start.Contains($"report:{l.Name}", StringComparison.Ordinal)).ToList();
                if (missing.Count == 0)
                    log.Add($"{lang}: start.txt already links all {Links.Length} toolkit reports");
                else
                {
                    var sb = new StringBuilder();
                    foreach (var (name, label) in missing)
                        sb.Append($"  * [[report:{name}|{label}]]\r");
                    // insert after the last existing toolkit link, else after the "default-compact" bullet, else append
                    int anchor = -1;
                    foreach (var l in Links)
                    {
                        int p = start.LastIndexOf($"report:{l.Name}", StringComparison.Ordinal);
                        if (p > anchor) anchor = p;
                    }
                    if (anchor < 0) anchor = start.IndexOf("default-compact", StringComparison.Ordinal);
                    if (anchor >= 0)
                    {
                        int eol = start.IndexOf('\r', anchor);
                        if (eol < 0) eol = start.Length;
                        start = start[..eol] + "\r" + sb.ToString().TrimEnd('\r') + start[eol..];
                    }
                    else start += "\r" + sb;
                    File.WriteAllText(startPath, start, enc);
                    log.Add($"{lang}: added {missing.Count} toolkit link(s) to start.txt");
                }
            }
        }
        log.Add(langs == 0 ? "no report folders found" : $"done — {langs} language folder(s)");
        return log;
    }
}
